default:  fxctmp9_tmp\ssao_ps30.inc shaders\fxc\ssao_ps30.vcs

fxctmp9_tmp\ssao_ps30.inc shaders\fxc\ssao_ps30.vcs: ssao_ps30.fxc common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h common_ps_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ssao_ps30.fxc-----ssao_ps30
	echo ssao_ps30.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

